server:
  port: 9093

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: UserProfileDB
      username: bilge
      password: bilge!123

authservice:
  secret:
    secret key: ${JAVA14_SECRET_KEY}
    issuer: ${JAVA14_ISSUER}
# docker run --name java14MongoDB -d -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=root mongo:jammy