server:
  port: 9094

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: SocialMediaPostDB
      username: bilge
      password: bilge!123



authservice:
  secret:
    secret key: ${JAVA14_SECRET_KEY}
    issuer: ${JAVA14_ISSUER}