server:
  port: 9092

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/SocialMediaDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

authservice:
  secret:
    secret key: ${JAVA14_SECRET_KEY}
    issuer: ${JAVA14_ISSUER}

